declare -gA EXP
EXP[NAME]="SoftObjects"
EXP[SING]="sing.simg"

declare -gA PATHS
PATHS[CUR_DIR]="$PWD"
PATHS[RAW_DATA_DIR]="$(dirname "$PWD")/${EXP[NAME]}/raw_data"
PATHS[RAW_EVENTS_DIR]="$(dirname "$PWD")/${EXP[NAME]}/raw_events"
PATHS[RAW_DATA_ZIP_DIR]="${PATHS[RAW_DATA_DIR]}/zipf"
PATHS[BIDS_DATA_DIR]="$(dirname "$PWD")/${EXP[NAME]}/data"
PATHS[PREPROCESSED_DATA_DIR]="$(dirname "$PWD")/${EXP[NAME]}/derivatives"
PATHS[FMRIPREP_WORK_DIR]="$(dirname "$PWD")/${EXP[NAME]}/fmriprep_workdir"
